### ISSUE TITLE
大佬，douyin的sign是咋抠出来的，能讲讲吗

### ISSUE THREAD

**Issue by ALASLI** [Leon406/pyutil#4]

**Comment by Leon406** [comment]
github搜索到的, 然后简化的

https://github.com/search?q=getXBoGust&type=code

**Comment by ALASLI** [comment]
好的 谢谢。是搜到的单独的sign的js 然后简化的吗，

**Comment by Leon406** [comment]
搜索签名参数 X-Bogus, 
https://github.com/search?q=X-Bogus

一个一个仓库或者代码去找的

**Comment by ALASLI** [comment]
好的 谢谢谢谢
